name: hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello sujit bhai
        run: echo "welcome to sujit bhai haveli"
        run: |
       echo "sujit bhai is hero"
       echo "sujit bhai is devops engineers"
       
        
